# Generated by Django 5.2.1 on 2025-06-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_alter_customuser_managers_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
