# Generated by Django 5.2.1 on 2025-06-09 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email cannot be blank.', 'required': 'Email is required.', 'unique': 'A user with this email already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(error_messages={'blank': 'Full name cannot be blank.', 'required': 'Full name is required.'}, max_length=255, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
