# Generated by Django 5.2.1 on 2025-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_remove_customuser_password_reset_token_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
